conmon: Add C99 or later guards to cmsg.c and conmon.c
Both of these files currently have issues with C90, as does glib.  For
example:

  $ make clean && make CFLAGS='-std=c90 -Wpedantic' conmon.o
  rm -f conmon.o cmsg.o ../bin/conmon
  cc -std=c90 -Wpedantic -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -DVERSION=\"1.9.0-dev\" -DGIT_COMMIT=\""be09ce7fb983fbd79fa65a8f9df4ceba2fc0d829-dirty"\"   -c -o conmon.o conmon.c
  In file included from /usr/lib64/glib-2.0/include/glibconfig.h:9:0,
                   from /usr/include/glib-2.0/glib/gtypes.h:32,
                   from /usr/include/glib-2.0/glib/galloca.h:32,
                   from /usr/include/glib-2.0/glib.h:30,
                   from conmon.c:25:
  /usr/include/glib-2.0/glib/gtypes.h: In function ‘_GLIB_CHECKED_ADD_U64’:
  /usr/include/glib-2.0/glib/gtypes.h:423:41: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
     G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
                                           ^
  ...
  conmon.c:30:20: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
   #define pexit(fmt, ...)                                                          \
                      ^~~
  ...

Instead of raising lots of individual warnings, use C99's
__STDC_VERSION__ [1] to error [2] for older versions.  Now you get:

  $ make clean && make CFLAGS='-std=c90' conmon.o
  rm -f conmon.o cmsg.o ../bin/conmon
  cc -std=c90 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -DVERSION=\"1.9.0-dev\" -DGIT_COMMIT=\""f904ba2de52af259f360d2a4d5dc07ba737e3c5c"\"   -c -o conmon.o conmon.c
  conmon.c:28:2: error: #error conmon.c requires C99 or later
   #error conmon.c requires C99 or later
    ^~~~~
  make: *** [<builtin>: conmon.o] Error 1

Previously, GCC would compile with C90, so this is being a bit more
strict.  But I prefer being safe to being optimistic about using
potentially unsupported features.

[1]: https://en.wikipedia.org/wiki/C99#Version_detection
[2]: https://gcc.gnu.org/onlinedocs/gcc-6.4.0/cpp/Diagnostics.html

Signed-off-by: W. Trevor King <wking@tremily.us>